# NER config 
SHARE:
    input:
    output:
NER: 
    # Paths to Datasets
    brat_train : ../../dataset/input/train/
    brat_dev : ../../dataset/input/dev/
    brat_test : ../../dataset/input/test/
    eval_result : ../evaluation/

    # Result path for saving predictions
    brat_folder : ../../dataset/outpput/dev/

    # Dataset Format
    tag_scheme : iob

    # Early stopping
    early_stopping_eps : 0
    early_stopping : 5


    # Model Settings
    model_type : 0
    epoch : 20
    replace_digit : true
    lowercase : false
    use_singletons : true
    # Train and predict gold : train+dev
    merge_train : true
    predict_train : true

    # Using Pretrained Embeddings
    #pre_emb : ../src/dataset/PubMed-shuffle-win-2.txt
    pre_emb :

    # Network Structure
    word_embedding_dim : 200
    char_embedding_dim : 15
    tag_embedding_dim : 5
    batch_size : 10

    # Hyperparameters
    dropout_ratio : 0.5
    lr_method : Adam
    lr_param : 0.01
    threshold : 5
    decay_rate : 0.00001

    # Tweak parameters
    bias : -0.5
    beta : 2

    # For Training and Tuning
    multi_gpus : {'main': -1}
    # training/tuning, mode: 'train', otherwise, mode:'test'
    mode : 'train'
    mappings_path : ../evaluation/mappings_0_cg.pkl

    # Evaluation
    path_model : ../result/model_iter_1382
    script_folder : ../script/
    result_folder : ../result/




# ================== Relation Extraction ====================== #
RE: 
    # model based
    model: re_model_base
    batchsize: 10
    epoch: 50
    bilstm_layers: 1
    word_dim: 200
    lstm_dim: 100
    out_dim: 100
    etype_dim: 10
    beta: 0.9
    pos_dim: 10
    dropi: 0.5
    dropm: 0.0
    dropo: 0.3
    learn: 0.001
    gradc: 10
    reg: 0.0001
    opt: adam
    patience: 5
    unk_w_prob: 0.01
    min_w_freq: 1
    
    # data based
    train_data: ../data/cg2013/train/
    test_data: ../data/cg2013/dev/
    embeds: ../../pre-train-embeds/PubMed-shuffle-win-2.txt
    save_fold: ../results
    name: sample_train
    pred_data: false
    save_pred: false
    
    # options (must be choosen from parse input)
    gpu: -1
    train: false
    tune: false
    test: false
    lowercase: false
    include_nested: true
    stats: false
    plot: false
    show_macro: false
    param_avg: false
    
    # extra
    datatype: document
    lab2ign: 1:Other:2
    early_metric: micro_f
    direction: l2r+r2l

EVENT:
    description: ''
    use_filter: False
    is_emo: True #True if .txt files contains sentence boundary information

    task: tune
    evaluation_script: "../model/evaluation/evaluation-CG-modified.py"
    interpreter: "python3 "
    dataset: CG13

    incl_intersen_events: True
    model: "/Users/kurt/Desktop/teesmodels/baseline/sbm_cg13.model"
    post_filter: True

    excl_train: {}
    excl_test: {}

    #for running experiments and saving outputs at every epoch
    starting_epoch_for_output: 5
    # ROOT_OUTPUT_COPY_FOLDER : "/Users/kurt/Desktop/" #must be the root folder for copy_tree to work
    # ROOT_OUTPUT_COPY_FOLDER : "/home/kjnosa/project/"
    root_output_copy_folder : "../../"
    epoch_output_folder : "epoch-output-folder/"

    #add "../" for pycharm debugging
    #SCENARIO 0
    train_dir : "../../dataset/tees/CG13/dev/"
    test_dir : "../../dataset/tees/CG13/devpred/"
    embedding_path : "../../embedding/PubMed-shuffle-win-2.txt"

    #NER
    train_ner : "../../dataset/tees/CG13/dev/"
    train_rel : "../../dataset/tees/CG13/dev/"
    #REL
    test_ner : "../../dataset/tees/CG13/devpred/"
    test_rel : "../../dataset/tees/CG13/devpred/"

    #SCENARIO 1
    # #NER
    # TRAIN_NER : "../dataset/input/train/"
    # TRAIN_REL : "../dataset/input/train/"
    # #REL
    # TEST_NER : "../dataset/output/dev/ner/recall/"
    # TEST_REL : "../dataset/output/dev/re/sc1_base/"

    #SCENARIO 2
    # #NER
    # TRAIN_NER : "../dataset/output/train/ner/recall/"
    # TRAIN_REL : "../dataset/output/train/re/sc2_ner-rec_re-base/"
    # #REL
    # TEST_NER : "../dataset/output/dev/ner/recall/"
    # TEST_REL : "../dataset/output/dev/re/sc2_ner-rec_re-base/"

    batch_size : 20
    max_epoch : 100
    patience : 5
    optimiser: "Adam"
    dropout : 0.5
    lr: 0.001
    weight_decay_rate: 0.001


    generalisation : 0 # Options: [0,1,2], 2 being Entity or Event

    unk_min_freq: 1 # determined from dataset
    unk_assign_prob : 0.2
    max_position: 130 #cg train data max is 122

    incl_mention : False
    partial_arg_matching : False
    threshold : 0.5
    replace_type : False
    n_best : 12
    margin : 0.0

    dim_position : 20 #so that same with types
    dim_embed : 200
    dim_event : 100
    dim_bilstm : 50
    dim_role_type : 10
    dim_arg_type : 20 #also used for trigger type as trigger can also be arguments
    dim_io : 2
    dim_action: 4

    events_with_numbered_roles : ['Binding', 'Planned_process', 'Pathway']
    special_entities : ['Protein_domain_or_region', 'DNA_domain_or_region']
